mkdir 01.BOM
mkdir 01.BOM_Review
mkdir 02.Schematic
mkdir 02.Schematic_Review
mkdir 03.Mechanism
mkdir 04.Layout
mkdir 04.Layout_Review
mkdir 04.Layout_Constraint_Rule
mkdir 04.Panel
mkdir 04.Stack-up
mkdir 05.Gerber
mkdir 06.Thermal
mkdir 07.FW_SW
mkdir 08.DVT
mkdir 09.HW_Spec
mkdir 10.SI_PI_Simulation_Report
mkdir 11.Release_Note
mkdir 12.Pilot_Run_Report
mkdir 13.Other_Info
mkdir 14.C23_related_Documents
mkdir 15.C4_related_Documents
touch Do_not_put_datasheet_in_the_folder.txt
touch Project_Members_List.txt
